# Generated by Django 3.2.8 on 2022-11-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0005_auto_20221102_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='subject',
        ),
        migrations.AddField(
            model_name='semester',
            name='subject',
            field=models.ManyToManyField(null=True, to='book_admin.Subject'),
        ),
    ]
