# Generated by Django 3.2.8 on 2022-11-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0006_auto_20221102_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='semester',
        ),
        migrations.AddField(
            model_name='branch',
            name='semester',
            field=models.ManyToManyField(null=True, to='book_admin.Semester'),
        ),
    ]
