# Generated by Django 3.2.8 on 2022-11-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_admin', '0007_auto_20221102_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='books',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_admin.book'),
        ),
    ]
