# Generated by Django 3.2.8 on 2022-11-01 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=5, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('condition', models.CharField(max_length=30, null=True)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transaction_img', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
